// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProjectManagement.Models;

namespace StudentProjectManagement.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentProjectManagement.Models.Grading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int?>("CriteriaId");

                    b.Property<int>("Grade");

                    b.Property<int?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Gradings");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.GradingCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GradePercentage");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("GradingCriterias");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved");

                    b.Property<string>("DocumentURL");

                    b.Property<int?>("ProjectId");

                    b.Property<string>("RejectedReason");

                    b.Property<string>("RejectionDate");

                    b.Property<DateTime>("SubmissionDate");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Grading", b =>
                {
                    b.HasOne("StudentProjectManagement.Models.GradingCriteria", "Criteria")
                        .WithMany("Gradings")
                        .HasForeignKey("CriteriaId");

                    b.HasOne("StudentProjectManagement.Models.Project", "Project")
                        .WithMany("Gradings")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Proposal", b =>
                {
                    b.HasOne("StudentProjectManagement.Models.Project", "Project")
                        .WithMany("Proposals")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("StudentProjectManagement.Models.Student", b =>
                {
                    b.HasOne("StudentProjectManagement.Models.Project", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
